
var LIBSVC = (function() {
    var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
    if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
    return (
  function(LIBSVC) {
    LIBSVC = LIBSVC || {};
  
  
  var e;e||(e=typeof LIBSVC !== 'undefined' ? LIBSVC : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},q;for(q in e)e.hasOwnProperty(q)&&(ca[q]=e[q]);var da="./this.program",ea=!1,v=!1,fa=!1,ha=!1;ea="object"===typeof window;v="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!v;var y="",ia,ja,ka,la,ma;
  if(fa)y=v?require("path").dirname(y)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),e.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=
  typeof read&&(ia=function(a){return read(a)}),ka=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||v)v?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),
  0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
  var na=e.print||console.log.bind(console),A=e.printErr||console.warn.bind(console);for(q in ca)ca.hasOwnProperty(q)&&(e[q]=ca[q]);ca=null;e.thisProgram&&(da=e.thisProgram);var oa;e.wasmBinary&&(oa=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var qa,ra=!1;function assert(a,b){a||z("Assertion failed: "+b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
  function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function B(a,b){return a?ta(C,a,b):""}
  function ua(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var k=a.charCodeAt(++g);l=65536+((l&1023)<<10)|k&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}function va(a,b,c){return ua(a,C,b,c)}
  function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var xa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function ya(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&za[c];)++c;c<<=1;if(32<c-a&&xa)return xa.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=F[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}
  function Aa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)F[b>>1]=a.charCodeAt(f),b+=2;F[b>>1]=0;return b-d}function Ba(a){return 2*a.length}function Ca(a,b){for(var c=0,d="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
  function Da(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Fa(a){var b=wa(a)+1,c=Ga(b);c&&ua(a,H,c,b);return c}var Ha,H,C,F,za,G,I,Ia,Ja;
  function Ka(){var a=qa.buffer;Ha=a;e.HEAP8=H=new Int8Array(a);e.HEAP16=F=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=za=new Uint16Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=Ia=new Float32Array(a);e.HEAPF64=Ja=new Float64Array(a)}var La,Ma=[],Na=[],Oa=[],Pa=[];Na.push({qb:function(){Qa()}});function Ra(){var a=e.preRun.shift();Ma.unshift(a)}var J=0,Sa=null,Ta=null;e.preloadedImages={};e.preloadedAudios={};
  function z(a){if(e.onAbort)e.onAbort(a);A(a);ra=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ua(a){var b=K;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Va(){return Ua("data:application/octet-stream;base64,")}var K="libsfu.prod.wasm";if(!Va()){var Wa=K;K=e.locateFile?e.locateFile(Wa,y):y+Wa}
  function Xa(){var a=K;try{if(a==K&&oa)return new Uint8Array(oa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
  function Ya(){if(!oa&&(ea||v)){if("function"===typeof fetch&&!Ua("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Xa()});if(ja)return new Promise(function(a,b){ja(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Xa()})}var L,Za;
  function $a(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.qb;"number"===typeof c?void 0===b.ab?La.get(c)():La.get(c)(b.ab):c(void 0===b.ab?null:b.ab)}}}var ab=[null,[],[]],bb={},cb={};function M(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function N(a){return this.fromWireType(I[a>>2])}var db={},O={},eb={};function fb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
  function gb(a,b){a=fb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function hb(a){var b=Error,c=gb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
  var ib=void 0;function jb(a){throw new ib(a);}function P(a,b,c){function d(k){k=c(k);k.length!==a.length&&jb("Mismatched type converter count");for(var m=0;m<a.length;++m)Q(a[m],k[m])}a.forEach(function(k){eb[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,m){O.hasOwnProperty(k)?f[m]=O[k]:(g.push(k),db.hasOwnProperty(k)||(db[k]=[]),db[k].push(function(){f[m]=O[k];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}var kb={};
  function lb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var mb=void 0;function R(a){for(var b="";C[a];)b+=mb[C[a++]];return b}var nb=void 0;function S(a){throw new nb(a);}
  function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.tb)return;S("Cannot register type '"+d+"' twice")}O[a]=b;delete eb[a];db.hasOwnProperty(a)&&(b=db[a],delete db[a],b.forEach(function(f){f()}))}function ob(a){return{count:a.count,Qa:a.Qa,Sa:a.Sa,Ea:a.Ea,Fa:a.Fa,Ia:a.Ia,La:a.La}}
  function pb(a){S(a.Ca.Fa.Da.name+" instance already deleted")}var qb=!1;function rb(){}function sb(a){--a.count.value;0===a.count.value&&(a.Ia?a.La.Ka(a.Ia):a.Fa.Da.Ka(a.Ea))}
  function tb(a){if("undefined"===typeof FinalizationGroup)return tb=function(b){return b},a;qb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Ea?sb(c):console.warn("object already deleted: "+c.Ea)});tb=function(b){qb.register(b,b.Ca,b.Ca);return b};rb=function(b){qb.unregister(b.Ca)};return tb(a)}var ub=void 0,vb=[];function wb(){for(;vb.length;){var a=vb.pop();a.Ca.Qa=!1;a["delete"]()}}function T(){}var xb={};
  function yb(a,b,c){if(void 0===a[b].Ga){var d=a[b];a[b]=function(){a[b].Ga.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ga+")!");return a[b].Ga[arguments.length].apply(this,arguments)};a[b].Ga=[];a[b].Ga[d.Pa]=d}}
  function zb(a,b){e.hasOwnProperty(a)?(S("Cannot register public name '"+a+"' twice"),yb(e,a,a),e.hasOwnProperty(void 0)&&S("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),e[a].Ga[void 0]=b):e[a]=b}function Ab(a,b,c,d,f,g,l,k){this.name=a;this.constructor=b;this.Na=c;this.Ka=d;this.Ma=f;this.rb=g;this.Va=l;this.ob=k;this.wb=[]}
  function Bb(a,b,c){for(;b!==c;)b.Va||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Va(a),b=b.Ma;return a}function Cb(a,b){if(null===b)return this.fb&&S("null is not a valid "+this.name),0;b.Ca||S('Cannot pass "'+Db(b)+'" as a '+this.name);b.Ca.Ea||S("Cannot pass deleted object as a pointer of type "+this.name);return Bb(b.Ca.Ea,b.Ca.Fa.Da,this.Da)}
  function Eb(a,b){if(null===b){this.fb&&S("null is not a valid "+this.name);if(this.Xa){var c=this.Ta();null!==a&&a.push(this.Ka,c);return c}return 0}b.Ca||S('Cannot pass "'+Db(b)+'" as a '+this.name);b.Ca.Ea||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Wa&&b.Ca.Fa.Wa&&S("Cannot convert argument of type "+(b.Ca.La?b.Ca.La.name:b.Ca.Fa.name)+" to parameter type "+this.name);c=Bb(b.Ca.Ea,b.Ca.Fa.Da,this.Da);if(this.Xa)switch(void 0===b.Ca.Ia&&S("Passing raw pointer to smart pointer is illegal"),
  this.yb){case 0:b.Ca.La===this?c=b.Ca.Ia:S("Cannot convert argument of type "+(b.Ca.La?b.Ca.La.name:b.Ca.Fa.name)+" to parameter type "+this.name);break;case 1:c=b.Ca.Ia;break;case 2:if(b.Ca.La===this)c=b.Ca.Ia;else{var d=b.clone();c=this.xb(c,U(function(){d["delete"]()}));null!==a&&a.push(this.Ka,c)}break;default:S("Unsupporting sharing policy")}return c}
  function Fb(a,b){if(null===b)return this.fb&&S("null is not a valid "+this.name),0;b.Ca||S('Cannot pass "'+Db(b)+'" as a '+this.name);b.Ca.Ea||S("Cannot pass deleted object as a pointer of type "+this.name);b.Ca.Fa.Wa&&S("Cannot convert argument of type "+b.Ca.Fa.name+" to parameter type "+this.name);return Bb(b.Ca.Ea,b.Ca.Fa.Da,this.Da)}function Gb(a,b,c){if(b===c)return a;if(void 0===c.Ma)return null;a=Gb(a,b,c.Ma);return null===a?null:c.ob(a)}var Hb={};
  function Ib(a,b){for(void 0===b&&S("ptr should not be undefined");a.Ma;)b=a.Va(b),a=a.Ma;return Hb[b]}function Jb(a,b){b.Fa&&b.Ea||jb("makeClassHandle requires ptr and ptrType");!!b.La!==!!b.Ia&&jb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return tb(Object.create(a,{Ca:{value:b}}))}
  function V(a,b,c,d){this.name=a;this.Da=b;this.fb=c;this.Wa=d;this.Xa=!1;this.Ka=this.xb=this.Ta=this.mb=this.yb=this.vb=void 0;void 0!==b.Ma?this.toWireType=Eb:(this.toWireType=d?Cb:Fb,this.Ja=null)}function Kb(a,b){e.hasOwnProperty(a)||jb("Replacing nonexistant public symbol");e[a]=b;e[a].Pa=void 0}
  function Lb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=La.get(b).apply(null,c);return f}}function W(a,b){a=R(a);var c=-1!=a.indexOf("j")?Lb(a,b):La.get(b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}
  var Mb=void 0;function Nb(a){a=Ob(a);var b=R(a);X(a);return b}function Pb(a,b){function c(g){f[g]||O[g]||(eb[g]?eb[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Mb(a+": "+d.map(Nb).join([", "]));}
  function Qb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=gb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
  function Rb(a,b,c,d,f){var g=b.length;2>g&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Ja){k=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<g-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+fb(a)+"("+p+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
  (g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var t=k?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[S,d,f,M,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);l&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(k)a+=
  "runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Ja&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",p.push(g+"_dtor"),d.push(b[c].Ja));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return Qb(p).apply(null,d)}function Sb(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
  function Tb(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.Da.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.Ca.Ea||S("cannot call emscripten binding method "+c+" on deleted object");return Bb(a.Ca.Ea,a.Ca.Fa.Da,b.Da)}var Ub=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Vb(a){4<a&&0===--Y[a].gb&&(Y[a]=void 0,Ub.push(a))}
  function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ub.length?Ub.pop():Y.length;Y[b]={gb:1,value:a};return b}}function Db(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Wb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ia[c>>2])};case 3:return function(c){return this.fromWireType(Ja[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
  function Xb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return C[d]};case 1:return c?function(d){return F[d>>1]}:function(d){return za[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Z(a){a||S("Cannot use deleted val. handle = "+a);return Y[a].value}function Zb(a,b){var c=O[a];void 0===c&&S(b+" has unknown type "+Nb(a));return c}
  function $b(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Zb(G[(b>>2)+d],"parameter "+d);return c}var ac={};function bc(a){var b=ac[a];return void 0===b?R(a):b}var cc=[];function dc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function ec(a){var b=cc.length;cc.push(a);return b}var fc;fa?fc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?fc=dateNow:fc=function(){return performance.now()};var hc={};
  function ic(){if(!jc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in hc)a[b]=hc[b];var c=[];for(b in a)c.push(b+"="+a[b]);jc=c}return jc}var jc;
  function kc(){function a(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}if(!lc){lc=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);G[mc()>>2]=60*g;G[nc()>>2]=Number(b!=f);c=a(c);d=a(d);c=Fa(c);d=Fa(d);f<b?(G[oc()>>2]=c,G[oc()+4>>2]=d):(G[oc()>>2]=d,G[oc()+4>>2]=c)}}var lc;function pc(a){return 0===a%4&&(0!==a%100||0===a%400)}function qc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
  var rc=[31,29,31,30,31,30,31,31,30,31,30,31],sc=[31,28,31,30,31,30,31,31,30,31,30,31];function tc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(pc(a.getFullYear())?rc:sc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
  function uc(a,b,c,d){function f(h,r,w){for(h="number"===typeof h?h.toString():h||"";h.length<r;)h=w[0]+h;return h}function g(h,r){return f(h,r,"0")}function l(h,r){function w(D){return 0>D?-1:0<D?1:0}var x;0===(x=w(h.getFullYear()-r.getFullYear()))&&0===(x=w(h.getMonth()-r.getMonth()))&&(x=w(h.getDate()-r.getDate()));return x}function k(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
  0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){h=tc(new Date(h.Ha+1900,0,1),h.$a);var r=new Date(h.getFullYear()+1,0,4),w=k(new Date(h.getFullYear(),0,4));r=k(r);return 0>=l(w,h)?0>=l(r,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var p=G[d+40>>2];d={Bb:G[d>>2],Ab:G[d+4>>2],Ya:G[d+8>>2],Ua:G[d+12>>2],Ra:G[d+16>>2],Ha:G[d+20>>2],Za:G[d+24>>2],$a:G[d+28>>2],Fb:G[d+32>>2],zb:G[d+
  36>>2],Cb:p?B(p):""};c=B(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
  u="January February March April May June July August September October November December".split(" ");p={"%a":function(h){return t[h.Za].substring(0,3)},"%A":function(h){return t[h.Za]},"%b":function(h){return u[h.Ra].substring(0,3)},"%B":function(h){return u[h.Ra]},"%C":function(h){return g((h.Ha+1900)/100|0,2)},"%d":function(h){return g(h.Ua,2)},"%e":function(h){return f(h.Ua,2," ")},"%g":function(h){return m(h).toString().substring(2)},"%G":function(h){return m(h)},"%H":function(h){return g(h.Ya,
  2)},"%I":function(h){h=h.Ya;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Ua+qc(pc(h.Ha+1900)?rc:sc,h.Ra-1),3)},"%m":function(h){return g(h.Ra+1,2)},"%M":function(h){return g(h.Ab,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Ya&&12>h.Ya?"AM":"PM"},"%S":function(h){return g(h.Bb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Za||7},"%U":function(h){var r=new Date(h.Ha+1900,0,1),w=0===r.getDay()?r:tc(r,7-r.getDay());h=new Date(h.Ha+1900,h.Ra,h.Ua);return 0>
  l(w,h)?g(Math.ceil((31-w.getDate()+(qc(pc(h.getFullYear())?rc:sc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(w,r)?"01":"00"},"%V":function(h){var r=new Date(h.Ha+1901,0,4),w=k(new Date(h.Ha+1900,0,4));r=k(r);var x=tc(new Date(h.Ha+1900,0,1),h.$a);return 0>l(x,w)?"53":0>=l(r,x)?"01":g(Math.ceil((w.getFullYear()<h.Ha+1900?h.$a+32-w.getDate():h.$a+1-w.getDate())/7),2)},"%w":function(h){return h.Za},"%W":function(h){var r=new Date(h.Ha,0,1),w=1===r.getDay()?r:tc(r,0===r.getDay()?1:7-r.getDay()+1);h=
  new Date(h.Ha+1900,h.Ra,h.Ua);return 0>l(w,h)?g(Math.ceil((31-w.getDate()+(qc(pc(h.getFullYear())?rc:sc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(w,r)?"01":"00"},"%y":function(h){return(h.Ha+1900).toString().substring(2)},"%Y":function(h){return h.Ha+1900},"%z":function(h){h=h.zb;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Cb},"%%":function(){return"%"}};for(n in p)0<=c.indexOf(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));n=
  vc(c);if(n.length>b)return 0;H.set(n,a);return n.length-1}ib=e.InternalError=hb("InternalError");for(var wc=Array(256),xc=0;256>xc;++xc)wc[xc]=String.fromCharCode(xc);mb=wc;nb=e.BindingError=hb("BindingError");T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.Ca.Fa.Da,c=this.Ca.Ea,d=a.Ca.Fa.Da;for(a=a.Ca.Ea;b.Ma;)c=b.Va(c),b=b.Ma;for(;d.Ma;)a=d.Va(a),d=d.Ma;return b===d&&c===a};
  T.prototype.clone=function(){this.Ca.Ea||pb(this);if(this.Ca.Sa)return this.Ca.count.value+=1,this;var a=tb(Object.create(Object.getPrototypeOf(this),{Ca:{value:ob(this.Ca)}}));a.Ca.count.value+=1;a.Ca.Qa=!1;return a};T.prototype["delete"]=function(){this.Ca.Ea||pb(this);this.Ca.Qa&&!this.Ca.Sa&&S("Object already scheduled for deletion");rb(this);sb(this.Ca);this.Ca.Sa||(this.Ca.Ia=void 0,this.Ca.Ea=void 0)};T.prototype.isDeleted=function(){return!this.Ca.Ea};
  T.prototype.deleteLater=function(){this.Ca.Ea||pb(this);this.Ca.Qa&&!this.Ca.Sa&&S("Object already scheduled for deletion");vb.push(this);1===vb.length&&ub&&ub(wb);this.Ca.Qa=!0;return this};V.prototype.sb=function(a){this.mb&&(a=this.mb(a));return a};V.prototype.kb=function(a){this.Ka&&this.Ka(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=N;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
  V.prototype.fromWireType=function(a){function b(){return this.Xa?Jb(this.Da.Na,{Fa:this.vb,Ea:c,La:this,Ia:a}):Jb(this.Da.Na,{Fa:this,Ea:a})}var c=this.sb(a);if(!c)return this.kb(a),null;var d=Ib(this.Da,c);if(void 0!==d){if(0===d.Ca.count.value)return d.Ca.Ea=c,d.Ca.Ia=a,d.clone();d=d.clone();this.kb(a);return d}d=this.Da.rb(c);d=xb[d];if(!d)return b.call(this);d=this.Wa?d.nb:d.pointerType;var f=Gb(c,this.Da,d.Da);return null===f?b.call(this):this.Xa?Jb(d.Da.Na,{Fa:d,Ea:f,La:this,Ia:a}):Jb(d.Da.Na,
  {Fa:d,Ea:f})};e.getInheritedInstanceCount=function(){return Object.keys(Hb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in Hb)Hb.hasOwnProperty(b)&&a.push(Hb[b]);return a};e.flushPendingDeletes=wb;e.setDelayFunction=function(a){ub=a;vb.length&&ub&&ub(wb)};Mb=e.UnboundTypeError=hb("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
  function vc(a){var b=Array(wa(a)+1);ua(a,b,0,b.length);return b}
  var zc={f:function(a,b,c,d){z("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,d?B(d):"unknown function"])},E:function(){return 42},Z:function(a){var b=cb[a];delete cb[a];var c=b.elements,d=c.length,f=c.map(function(k){return k.eb}).concat(c.map(function(k){return k.ib})),g=b.Ta,l=b.Ka;P([a],f,function(k){c.forEach(function(m,p){var n=k[p],t=m.bb,u=m.cb,h=k[p+d],r=m.hb,w=m.jb;m.read=function(x){return n.fromWireType(t(u,x))};m.write=function(x,D){var E=[];r(w,x,h.toWireType(E,D));M(E)}});
  return[{name:b.name,fromWireType:function(m){for(var p=Array(d),n=0;n<d;++n)p[n]=c[n].read(m);l(m);return p},toWireType:function(m,p){if(d!==p.length)throw new TypeError("Incorrect number of tuple elements for "+b.name+": expected="+d+", actual="+p.length);for(var n=g(),t=0;t<d;++t)c[t].write(n,p[t]);null!==m&&m.push(l,n);return n},argPackAdvance:8,readValueFromPointer:N,Ja:l}]})},p:function(a){var b=kb[a];delete kb[a];var c=b.Ta,d=b.Ka,f=b.lb,g=f.map(function(l){return l.eb}).concat(f.map(function(l){return l.ib}));
  P([a],g,function(l){var k={};f.forEach(function(m,p){var n=l[p],t=m.bb,u=m.cb,h=l[p+f.length],r=m.hb,w=m.jb;k[m.pb]={read:function(x){return n.fromWireType(t(u,x))},write:function(x,D){var E=[];r(w,x,h.toWireType(E,D));M(E)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in k)p[n]=k[n].read(m);d(m);return p},toWireType:function(m,p){for(var n in k)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var t=c();for(n in k)k[n].write(t,p[n]);null!==m&&m.push(d,t);return t},argPackAdvance:8,
  readValueFromPointer:N,Ja:d}]})},W:function(a,b,c,d,f){var g=lb(c);b=R(b);Q(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=H;else if(2===c)k=F;else if(4===c)k=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},Ja:null})},u:function(a,b,c,d,f,g,l,k,m,p,n,t,u){n=R(n);g=W(f,g);k&&(k=W(l,k));p&&(p=W(m,p));u=W(t,u);var h=fb(n);zb(h,function(){Pb("Cannot construct "+
  n+" due to unbound types",[d])});P([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var w=r.Da;var x=w.Na}else x=T.prototype;r=gb(h,function(){if(Object.getPrototypeOf(this)!==D)throw new nb("Use 'new' to construct "+n);if(void 0===E.Oa)throw new nb(n+" has no accessible constructor");var Yb=E.Oa[arguments.length];if(void 0===Yb)throw new nb("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(E.Oa).toString()+") parameters instead!");return Yb.apply(this,
  arguments)});var D=Object.create(x,{constructor:{value:r}});r.prototype=D;var E=new Ab(n,r,D,u,w,g,k,p);w=new V(n,E,!0,!1);x=new V(n+"*",E,!1,!1);var pa=new V(n+" const*",E,!1,!0);xb[a]={pointerType:x,nb:pa};Kb(h,r);return[w,x,pa]})},x:function(a,b,c,d,f,g,l){var k=Sb(c,d);b=R(b);g=W(f,g);P([],[a],function(m){function p(){Pb("Cannot call "+n+" due to unbound types",k)}m=m[0];var n=m.name+"."+b,t=m.Da.constructor;void 0===t[b]?(p.Pa=c-1,t[b]=p):(yb(t,b,n),t[b].Ga[c-1]=p);P([],k,function(u){u=[u[0],
  null].concat(u.slice(1));u=Rb(n,u,null,g,l);void 0===t[b].Ga?(u.Pa=c-1,t[b]=u):t[b].Ga[c-1]=u;return[]});return[]})},t:function(a,b,c,d,f,g){assert(0<b);var l=Sb(b,c);f=W(d,f);var k=[g],m=[];P([],[a],function(p){p=p[0];var n="constructor "+p.name;void 0===p.Da.Oa&&(p.Da.Oa=[]);if(void 0!==p.Da.Oa[b-1])throw new nb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+p.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
  p.Da.Oa[b-1]=function(){Pb("Cannot construct "+p.name+" due to unbound types",l)};P([],l,function(t){p.Da.Oa[b-1]=function(){arguments.length!==b-1&&S(n+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;k.length=b;for(var u=1;u<b;++u)k[u]=t[u].toWireType(m,arguments[u-1]);u=f.apply(null,k);M(m);return t[0].fromWireType(u)};return[]});return[]})},l:function(a,b,c,d,f,g,l,k){var m=Sb(c,d);b=R(b);g=W(f,g);P([],[a],function(p){function n(){Pb("Cannot call "+t+" due to unbound types",
  m)}p=p[0];var t=p.name+"."+b;k&&p.Da.wb.push(b);var u=p.Da.Na,h=u[b];void 0===h||void 0===h.Ga&&h.className!==p.name&&h.Pa===c-2?(n.Pa=c-2,n.className=p.name,u[b]=n):(yb(u,b,t),u[b].Ga[c-2]=n);P([],m,function(r){r=Rb(t,r,p,g,l);void 0===u[b].Ga?(r.Pa=c-2,u[b]=r):u[b].Ga[c-2]=r;return[]});return[]})},L:function(a,b,c,d,f,g,l,k,m,p){b=R(b);f=W(d,f);P([],[a],function(n){n=n[0];var t=n.name+"."+b,u={get:function(){Pb("Cannot access "+t+" due to unbound types",[c,l])},enumerable:!0,configurable:!0};m?
  u.set=function(){Pb("Cannot access "+t+" due to unbound types",[c,l])}:u.set=function(){S(t+" is a read-only property")};Object.defineProperty(n.Da.Na,b,u);P([],m?[c,l]:[c],function(h){var r=h[0],w={get:function(){var D=Tb(this,n,t+" getter");return r.fromWireType(f(g,D))},enumerable:!0};if(m){m=W(k,m);var x=h[1];w.set=function(D){var E=Tb(this,n,t+" setter"),pa=[];m(p,E,x.toWireType(pa,D));M(pa)}}Object.defineProperty(n.Da.Na,b,w);return[]});return[]})},V:function(a,b){b=R(b);Q(a,{name:b,fromWireType:function(c){var d=
  Y[c].value;Vb(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:N,Ja:null})},G:function(a,b,c){c=lb(c);b=R(b);Q(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Db(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Wb(b,c),Ja:null})},o:function(a,b,c,d,f){function g(p){return p}b=R(b);-1===f&&(f=4294967295);var l=lb(c);if(0===d){var k=32-
  8*c;g=function(p){return p<<k>>>k}}var m=-1!=b.indexOf("unsigned");Q(a,{name:b,fromWireType:g,toWireType:function(p,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Db(n)+'" to '+this.name);if(n<d||n>f)throw new TypeError('Passing a number "'+Db(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Xb(b,l,0!==d),Ja:null})},n:function(a,b,c){function d(g){g>>=
  2;var l=I;return new f(Ha,l[g+1],l[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{tb:!0})},H:function(a,b){b=R(b);var c="std::string"===b;Q(a,{name:b,fromWireType:function(d){var f=I[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var k=d+4+l;if(l==f||0==C[k]){g=B(g,k-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=k+1}}else{m=Array(f);for(l=0;l<f;++l)m[l]=
  String.fromCharCode(C[d+4+l]);m=m.join("")}X(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&g?function(){return wa(f)}:function(){return f.length})(),k=Ga(4+l+1);I[k>>2]=l;if(c&&g)va(f,k+4,l+1);else if(g)for(g=0;g<l;++g){var m=f.charCodeAt(g);255<m&&(X(k),S("String has UTF-16 code units that do not fit in 8 bits"));
  C[k+4+g]=m}else for(g=0;g<l;++g)C[k+4+g]=f[g];null!==d&&d.push(X,k);return k},argPackAdvance:8,readValueFromPointer:N,Ja:function(d){X(d)}})},y:function(a,b,c){c=R(c);if(2===b){var d=ya;var f=Aa;var g=Ba;var l=function(){return za};var k=1}else 4===b&&(d=Ca,f=Da,g=Ea,l=function(){return I},k=2);Q(a,{name:c,fromWireType:function(m){for(var p=I[m>>2],n=l(),t,u=m+4,h=0;h<=p;++h){var r=m+4+h*b;if(h==p||0==n[r>>k])u=d(u,r-u),void 0===t?t=u:(t+=String.fromCharCode(0),t+=u),u=r+b}X(m);return t},toWireType:function(m,
  p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var n=g(p),t=Ga(4+n+b);I[t>>2]=n>>k;f(p,t+4,n+b);null!==m&&m.push(X,t);return t},argPackAdvance:8,readValueFromPointer:N,Ja:function(m){X(m)}})},_:function(a,b,c,d,f,g){cb[a]={name:R(b),Ta:W(c,d),Ka:W(f,g),elements:[]}},K:function(a,b,c,d,f,g,l,k,m){cb[a].elements.push({eb:b,bb:W(c,d),cb:f,ib:g,hb:W(l,k),jb:m})},q:function(a,b,c,d,f,g){kb[a]={name:R(b),Ta:W(c,d),Ka:W(f,g),lb:[]}},i:function(a,b,c,d,f,g,l,k,m,p){kb[a].lb.push({pb:R(b),
  eb:c,bb:W(d,f),cb:g,ib:l,hb:W(k,m),jb:p})},X:function(a,b){b=R(b);Q(a,{ub:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},c:function(a,b,c){a=Z(a);b=Zb(b,"emval::as");var d=[],f=U(d);G[c>>2]=f;return b.toWireType(d,a)},j:function(a,b,c,d){a=Z(a);c=$b(b,c);for(var f=Array(b),g=0;g<b;++g){var l=c[g];f[g]=l.readValueFromPointer(d);d+=l.argPackAdvance}a=a.apply(void 0,f);return U(a)},C:function(a,b,c,d,f){a=cc[a];b=Z(b);c=bc(c);var g=[];G[d>>2]=U(g);return a(b,c,g,f)},
  v:function(a,b,c,d){a=cc[a];b=Z(b);c=bc(c);a(b,c,null,d)},a:Vb,k:function(a,b){a=Z(a);b=Z(b);return delete a[b]},A:function(a){if(0===a)return U(dc());a=bc(a);return U(dc()[a])},r:function(a,b){b=$b(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",f=["retType"],g=[c],l="",k=0;k<a-1;++k)l+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),g.push(b[1+k]);d="return function "+fb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(k=0;k<a-1;++k)d+=
  "    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[k+1].argPackAdvance;d+="    var rv = handle[name]("+l+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+k+".deleteObject(arg"+k+");\n");c.ub||(d+="    return retType.toWireType(destructors, rv);\n");f.push(d+"};\n");a=Qb(f).apply(null,g);return ec(a)},h:function(a,b){a=Z(a);b=Z(b);return U(a[b])},e:function(a){4<a&&(Y[a].gb+=1)},B:function(a,b){a=Z(a);b=Z(b);return a instanceof b},J:function(){return U([])},
  d:function(a){return U(bc(a))},P:function(a){a=Z(a);return!a},b:function(a){M(Y[a].value);Vb(a)},$:function(a,b,c){a=Z(a);b=Z(b);c=Z(c);a[b]=c},M:function(a,b){a=Z(a);b=Z(b);return a===b},w:function(a,b){a=Zb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},m:function(){z()},z:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=fc();else return G[yc()>>2]=28,-1;G[b>>2]=a/1E3|0;G[b+4>>2]=a%1E3*1E6|0;return 0},O:function(a,b,c){C.copyWithin(a,b,b+c)},s:function(a){a>>>=0;var b=
  C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{qa.grow(Math.min(2147483648,d)-Ha.byteLength+65535>>>16);Ka();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},R:function(a,b){var c=0;ic().forEach(function(d,f){var g=b+c;f=G[a+4*f>>2]=g;for(g=0;g<d.length;++g)H[f++>>0]=d.charCodeAt(g);H[f>>0]=0;c+=d.length+1});return 0},S:function(a,b){var c=ic();G[a>>2]=c.length;var d=0;c.forEach(function(f){d+=
  f.length+1});G[b>>2]=d;return 0},U:function(){return 0},T:function(a,b,c,d){a=bb.Eb(a);b=bb.Db(a,b,c);G[d>>2]=b;return 0},N:function(){},F:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var l=G[b+8*g>>2],k=G[b+(8*g+4)>>2],m=0;m<k;m++){var p=C[l+m],n=ab[a];0===p||10===p?((1===a?na:A)(ta(n,0)),n.length=0):n.push(p)}f+=k}G[d>>2]=f;return 0},g:function(a){var b=Date.now();G[a>>2]=b/1E3|0;G[a+4>>2]=b%1E3*1E3|0;return 0},I:function(a,b){kc();a=new Date(1E3*G[a>>2]);G[b>>2]=a.getSeconds();G[b+4>>2]=a.getMinutes();
  G[b+8>>2]=a.getHours();G[b+12>>2]=a.getDate();G[b+16>>2]=a.getMonth();G[b+20>>2]=a.getFullYear()-1900;G[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);G[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;G[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;G[b+32>>2]=a;a=G[oc()+(a?4:0)>>2];G[b+40>>2]=a;return b},Y:function(){return 28},D:function(){},Q:function(a,b,c,d){return uc(a,
  b,c,d)}};
  (function(){function a(f){e.asm=f.exports;qa=e.asm.aa;Ka();La=e.asm.ba;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta&&(f=Ta,Ta=null,f()))}function b(f){a(f.instance)}function c(f){return Ya().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){A("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:zc};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+
  f),!1}(function(){return oa||"function"!==typeof WebAssembly.instantiateStreaming||Va()||Ua("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){A("wasm streaming compile failed: "+g);A("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
  var Qa=e.___wasm_call_ctors=function(){return(Qa=e.___wasm_call_ctors=e.asm.ca).apply(null,arguments)},Ga=e._malloc=function(){return(Ga=e._malloc=e.asm.da).apply(null,arguments)},X=e._free=function(){return(X=e._free=e.asm.ea).apply(null,arguments)},yc=e.___errno_location=function(){return(yc=e.___errno_location=e.asm.fa).apply(null,arguments)},Ob=e.___getTypeName=function(){return(Ob=e.___getTypeName=e.asm.ga).apply(null,arguments)};
  e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.ha).apply(null,arguments)};var oc=e.__get_tzname=function(){return(oc=e.__get_tzname=e.asm.ia).apply(null,arguments)},nc=e.__get_daylight=function(){return(nc=e.__get_daylight=e.asm.ja).apply(null,arguments)},mc=e.__get_timezone=function(){return(mc=e.__get_timezone=e.asm.ka).apply(null,arguments)};e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.la).apply(null,arguments)};
  e.dynCall_viij=function(){return(e.dynCall_viij=e.asm.ma).apply(null,arguments)};e.dynCall_iiiij=function(){return(e.dynCall_iiiij=e.asm.na).apply(null,arguments)};e.dynCall_vijii=function(){return(e.dynCall_vijii=e.asm.oa).apply(null,arguments)};e.dynCall_iij=function(){return(e.dynCall_iij=e.asm.pa).apply(null,arguments)};e.dynCall_viiij=function(){return(e.dynCall_viiij=e.asm.qa).apply(null,arguments)};e.dynCall_viiijii=function(){return(e.dynCall_viiijii=e.asm.ra).apply(null,arguments)};
  e.dynCall_vij=function(){return(e.dynCall_vij=e.asm.sa).apply(null,arguments)};e.dynCall_iiij=function(){return(e.dynCall_iiij=e.asm.ta).apply(null,arguments)};e.dynCall_viiiij=function(){return(e.dynCall_viiiij=e.asm.ua).apply(null,arguments)};e.dynCall_ji=function(){return(e.dynCall_ji=e.asm.va).apply(null,arguments)};e.dynCall_viiji=function(){return(e.dynCall_viiji=e.asm.wa).apply(null,arguments)};e.dynCall_viji=function(){return(e.dynCall_viji=e.asm.xa).apply(null,arguments)};
  e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.ya).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.za).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.Aa).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.Ba).apply(null,arguments)};e._ff_h264_cabac_tables=43984;
  e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":H[a>>0]=b;break;case "i8":H[a>>0]=b;break;case "i16":F[a>>1]=b;break;case "i32":G[a>>2]=b;break;case "i64":Za=[b>>>0,(L=b,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];G[a>>2]=Za[0];G[a+4>>2]=Za[1];break;case "float":Ia[a>>2]=b;break;case "double":Ja[a>>3]=b;break;default:z("invalid type for setValue: "+c)}};
  e.getValue=function(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return H[a>>0];case "i8":return H[a>>0];case "i16":return F[a>>1];case "i32":return G[a>>2];case "i64":return G[a>>2];case "float":return Ia[a>>2];case "double":return Ja[a>>3];default:z("invalid type for getValue: "+b)}return null};e.UTF8ToString=B;e.stringToUTF8=va;var Ac;Ta=function Bc(){Ac||Cc();Ac||(Ta=Bc)};
  function Cc(){function a(){if(!Ac&&(Ac=!0,e.calledRun=!0,!ra)){$a(Na);$a(Oa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Pa.unshift(b)}$a(Pa)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ra();$a(Ma);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
  e.run=Cc;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Cc();
  
  
    return LIBSVC.ready
  }
  );
  })();
  if (typeof exports === 'object' && typeof module === 'object')
    module.exports = LIBSVC;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return LIBSVC; });
  else if (typeof exports === 'object')
    exports["LIBSVC"] = LIBSVC;
  /* eslint-disable */
  (function (LIBSVC) {
    var SFUTransportType = {};
    SFUTransportType[(SFUTransportType['kAudio'] = 1)] = 'kAudio';
    SFUTransportType[(SFUTransportType['kVideo'] = 2)] = 'kVideo';
    SFUTransportType[(SFUTransportType['kData'] = 3)] = 'kData';
    SFUTransportType[(SFUTransportType['kAnnotation'] = 4)] = 'kAnnotation';
  
    var SFUTransportOrient = {};
    SFUTransportOrient[(SFUTransportOrient['kSend'] = 1)] = 'kSend';
    SFUTransportOrient[(SFUTransportOrient['kRecv'] = 2)] = 'kRecv';
    SFUTransportOrient[(SFUTransportOrient['kBoth'] = 3)] = 'kBoth';
  
    var SFUUserRole = {};
    SFUUserRole[(SFUUserRole['kInteractive'] = 1)] = 'kInteractive';
    SFUUserRole[(SFUUserRole['kBroadcast'] = 2)] = 'kBroadcast';
  
    var SFUReason = {};
    SFUReason[(SFUReason['kOK'] = 0)] = 'kOK';
    SFUReason[(SFUReason['kError'] = 320200)] = 'kError';
    SFUReason[(SFUReason['kExisted'] = 3202001)] = 'kExisted';
    SFUReason[(SFUReason['kNetworkError'] = 320202)] = 'kNetworkError';
    SFUReason[(SFUReason['kMCFailed'] = 320203)] = 'kMCFailed';
    SFUReason[(SFUReason['kMSSFailed'] = 320204)] = 'kMSSFailed';
    SFUReason[(SFUReason['kMSSLost'] = 320205)] = 'kMSSLost';
    SFUReason[(SFUReason['kAuthFailed'] = 320206)] = 'kAuthFailed';
    SFUReason[(SFUReason['kErkLoadFailedror'] = 320207)] = 'kLoadFailed';
    SFUReason[(SFUReason['kNoImplemented'] = 320208)] = 'kNoImplemented';
  
    var SFUTransportStatus = {};
    SFUTransportStatus[(SFUTransportStatus['kReconnecting'] = 320100)] =
      'kReconnecting';
    SFUTransportStatus[(SFUTransportStatus['kReconnectOK'] = 320101)] =
      'kReconnectOK';
    SFUTransportStatus[(SFUTransportStatus['kReconnectNG'] = 320102)] =
      'kReconnectNG';
  
    var SFUEndpointStatus = {};
    SFUEndpointStatus[(SFUEndpointStatus['kHandshakeOK'] = 100)] = 'kHandshakeOK';
    SFUEndpointStatus[(SFUEndpointStatus['kHandshakeNG'] = 101)] =
      'kReconnkHandshakeNGectOK';
    SFUEndpointStatus[(SFUEndpointStatus['kConnectOK'] = 102)] = 'kConnectOK';
    SFUEndpointStatus[(SFUEndpointStatus['kConnectNG'] = 103)] = 'kConnectNG';
  
    var VideoChannelType = {};
    VideoChannelType[(VideoChannelType['kAudio'] = 1)] = 'kAudio';
    VideoChannelType[(VideoChannelType['kVideo'] = 2)] = 'kVideo';
    VideoChannelType[(VideoChannelType['kData'] = 3)] = 'kData';
    VideoChannelType[(VideoChannelType['kAnnotation'] = 4)] = 'kAnnotation';
  
    var VideoChannelOrient = {};
    VideoChannelOrient[(VideoChannelOrient['kSend'] = 1)] = 'kSend';
    VideoChannelOrient[(VideoChannelOrient['kRecv'] = 2)] = 'kRecv';
    VideoChannelOrient[(VideoChannelOrient['kBoth'] = 3)] = 'kBoth';
  
    var VideoChannelMode = {};
    VideoChannelMode[(VideoChannelMode['kNormal'] = 0)] = 'kNormal';
    VideoChannelMode[(VideoChannelMode['kSmooth'] = 1)] = 'kSmooth';
  
    var VideoRotation = {};
    VideoRotation[(VideoRotation['kRotation_0'] = 0)] = 'kRotation_0';
    VideoRotation[(VideoRotation['kRotation_90'] = 90)] = 'kRotation_90';
    VideoRotation[(VideoRotation['kRotation_180'] = 180)] = 'kRotation_180';
    VideoRotation[(VideoRotation['kRotation_270'] = 270)] = 'kRotation_270';
  
    var TransportType = {};
    TransportType[(TransportType['kSignal'] = 0)] = 'kSignal';
    TransportType[(TransportType['kData'] = 1)] = 'kData';
  
    LIBSVC['SFUReason'] = SFUReason;
    LIBSVC['SFUUserRole'] = SFUUserRole;
    LIBSVC['SFUTransportType'] = SFUTransportType;
    LIBSVC['SFUTransportStatus'] = SFUTransportStatus;
    LIBSVC['SFUTransportOrient'] = SFUTransportOrient;
    LIBSVC['SFUEndpointStatus'] = SFUEndpointStatus;
    LIBSVC['VideoChannelType'] = VideoChannelType;
    LIBSVC['VideoChannelOrient'] = VideoChannelOrient;
    LIBSVC['TransportType'] = TransportType;
    LIBSVC['VideoChannelMode'] = VideoChannelMode;
    LIBSVC['VideoRotation'] = VideoRotation;
  })(LIBSVC || (LIBSVC = {}));
  /* eslint-enable */
  
  